//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public int CreatorID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> ValueChainID { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int FlagsID { get; set; }
        public bool IsDefault { get; set; }
        public string AttachmentsJson { get; set; }
        public Nullable<System.Guid> AttachmentID { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual Course Course { get; set; }
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
        public virtual ValueChain ValueChain { get; set; }
    }
}
