//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Articles = new HashSet<Article>();
            this.CoursePrices = new HashSet<CoursePrice>();
            this.Crops = new HashSet<Crop>();
            this.Examinations = new HashSet<Examination>();
            this.UserDeductions = new HashSet<UserDeduction>();
            this.Livestocks = new HashSet<Livestock>();
            this.Modules = new HashSet<Module>();
            this.UserExaminations = new HashSet<UserExamination>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int CreatorID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Description { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> ValueChainID { get; set; }
        public Nullable<int> NonValueChainID { get; set; }
        public string Glossary { get; set; }
        public string AttachmentsJson { get; set; }
        public Nullable<System.Guid> IconID { get; set; }
        public Nullable<int> FinalExamQuestions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Attachment Attachment { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual NonValueChain NonValueChain { get; set; }
        public virtual User User { get; set; }
        public virtual ValueChain ValueChain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursePrice> CoursePrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crop> Crops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination> Examinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDeduction> UserDeductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livestock> Livestocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Module> Modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExamination> UserExaminations { get; set; }
    }
}
