//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationPrice
    {
        public int ID { get; set; }
        public int ExaminationID { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatorID { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Examination Examination { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual User User { get; set; }
    }
}
