//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examination()
        {
            this.ExaminationAttemptCounts = new HashSet<ExaminationAttemptCount>();
            this.ExaminationPrices = new HashSet<ExaminationPrice>();
            this.UserDeductions = new HashSet<UserDeduction>();
            this.UserExaminations = new HashSet<UserExamination>();
            this.Questions = new HashSet<Question>();
        }
    
        public int ID { get; set; }
        public string Topic { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public int Year { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int TypeID { get; set; }
        public decimal Duration { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> MaxAttempts { get; set; }
        public string AttachmentsJson { get; set; }
        public Nullable<int> ValueChainID { get; set; }
        public int CreatorID { get; set; }
        public int PaperFormatID { get; set; }
        public int FlagsID { get; set; }
        public int TargetAudienceID { get; set; }
        public int NumberOfQuestions { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
        public virtual ValueChain ValueChain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationAttemptCount> ExaminationAttemptCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationPrice> ExaminationPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDeduction> UserDeductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExamination> UserExaminations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
    }
}
