//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtensionOfficer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExtensionOfficer()
        {
            this.Users = new HashSet<User>();
        }
    
        public System.Guid ID { get; set; }
        public string ECNumber { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string NationalID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual District District { get; set; }
        public virtual Province Province { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
