//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livestock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livestock()
        {
            this.Livestock1 = new HashSet<Livestock>();
        }
    
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CreatorID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<System.Guid> IconID { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livestock> Livestock1 { get; set; }
        public virtual Livestock Livestock2 { get; set; }
        public virtual LivestockCategory LivestockCategory { get; set; }
        public virtual User User { get; set; }
    }
}
