//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InServiceEntities : DbContext
    {
        public InServiceEntities()
            : base("name=InServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Continent> Continents { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CoursePrice> CoursePrices { get; set; }
        public virtual DbSet<Crop> Crops { get; set; }
        public virtual DbSet<CropCategory> CropCategories { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<EmailConfig> EmailConfigs { get; set; }
        public virtual DbSet<Examination> Examinations { get; set; }
        public virtual DbSet<ExaminationAttemptCount> ExaminationAttemptCounts { get; set; }
        public virtual DbSet<ExaminationPrice> ExaminationPrices { get; set; }
        public virtual DbSet<ExchangeRate> ExchangeRates { get; set; }
        public virtual DbSet<ExtensionOfficer> ExtensionOfficers { get; set; }
        public virtual DbSet<Farmer> Farmers { get; set; }
        public virtual DbSet<Instruction> Instructions { get; set; }
        public virtual DbSet<Livestock> Livestocks { get; set; }
        public virtual DbSet<LivestockCategory> LivestockCategories { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<NonValueChain> NonValueChains { get; set; }
        public virtual DbSet<Notice> Notices { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserDeduction> UserDeductions { get; set; }
        public virtual DbSet<UserExamination> UserExaminations { get; set; }
        public virtual DbSet<UserExaminationDetail> UserExaminationDetails { get; set; }
        public virtual DbSet<ValueChain> ValueChains { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
    }
}
