//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public System.Guid ID { get; set; }
        public string Heading { get; set; }
        public string Description { get; set; }
        public string AttachmentsJson { get; set; }
        public int CreatorID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int StatusID { get; set; }
        public int TypeID { get; set; }
        public Nullable<System.Guid> AttachmentID { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual User User { get; set; }
    }
}
