//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExaminationDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid ExaminationID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public string Name { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual UserExamination UserExamination { get; set; }
    }
}
