//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExamination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserExamination()
        {
            this.UserExaminationDetails = new HashSet<UserExaminationDetail>();
        }
    
        public System.Guid ID { get; set; }
        public int UserID { get; set; }
        public int ExaminationID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string AttachmentsJson { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int CourseID { get; set; }
        public int ModuleID { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Examination Examination { get; set; }
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExaminationDetail> UserExaminationDetails { get; set; }
    }
}
